language: python

sudo: false  # false enables container-based build for fast boot times on Linux

matrix:
    include:
        - os: linux
          python: 3.5
          env: TOXENV=py35
        - os: linux
          python: 3.6
          env: TOXENV=py36
        - os: linux
          python: 3.7
          dist: xenial
          env: TOXENV=py37
        - os: linux
          python: 3.8
          dist: xenial
          env: TOXENV=py38
        - os: linux
          python: 3.9-dev
          dist: xenial
          env: TOXENV=py39
#        # Warning: Don't try to use code coverage analysis with pypy as it is insanely slow
#        - os: linux
#          python: pypy3
#          env: TOXENV=pypy3
#        # Latest Python 3.x from Homebrew
#        - os: osx
#          language: generic
#          env:
#            - TOXENV=py36
#            - BREW_INSTALL=python3

install:
  - pip install tox
#  - |
#    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
#      if [[ -n "$BREW_INSTALL" ]]; then
#        brew update
#        brew install "$BREW_INSTALL"
#      fi
#    fi
#    pip install tox

script:
  - tox
